plugins {
    id 'com.android.application'
}

android {
    namespace 'com.myvpn.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.myvpn.app'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'])
}
